create table if not exists public.analysis_history (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid()
        references auth.users (id) on delete cascade,
    created_at timestamptz not null default now(),
    input_text text not null,
    risk_score integer not null check (risk_score between 0 and 100),
    risk_level text not null,
    category text not null,
    red_flags jsonb not null default '[]'::jsonb,
    actions jsonb not null default '[]'::jsonb,
    conclusion text not null
);

alter table public.analysis_history enable row level security;

revoke all on table public.analysis_history from anon;
grant select, insert on table public.analysis_history to authenticated;
grant usage, select on sequence public.analysis_history_id_seq to authenticated;

drop policy if exists "Users can read their own history"
    on public.analysis_history;
create policy "Users can read their own history"
    on public.analysis_history
    for select
    to authenticated
    using ((select auth.uid()) = user_id);

drop policy if exists "Users can add their own history"
    on public.analysis_history;
create policy "Users can add their own history"
    on public.analysis_history
    for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

create index if not exists analysis_history_user_created_idx
    on public.analysis_history (user_id, created_at desc);
